version: '3.4'

services:
   catalogdb:
     container_name: catalogdb
     restart: always
     volumes:
        #- mongo_data:/data/db
       # - ${WEBAPP_STORAGE_HOME}/site:/data/db
       - ./data:/data/db
     ports:
            - "27017:27017"
   basketdb:
     container_name: basketdb
     restart: always    
     ports:
       - "6379:6379"

   #add rabbitmq
   rabbitmq:
       container_name: rabbitmq
       restart: always
       ports:
           - "5672:5672"
           - "15672:15672"

    #add data from sql server
   orderdb:
       container_name: orderdb
       ports:
           - "1433:1433"
       environment:
           SA_PASSWORD: "SwN12345678"
           ACCEPT_EULA: "Y"

   # add portiner
   portainer:
     container_name: portainer
     restart: always
     ports:
       - "8080:8000"
       - "9000:9000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data

    #add postgres
   discountdb:
     container_name: discountdb
     environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=admin1234
       - POSTGRES_DB=DiscountDb
     restart: always
     ports:
         - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data/

 # add pagadmin
   pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

#catalog
   catalogapi:
     container_name: catalogapi
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
     depends_on:
      - catalogdb
     ports:
      - "8000:80"

      #add basket
   basketapii:
     container_name: basketapii
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - "CacheSettings:ConnectionString=basketdb:6379"
       - "EventBus:HostName=rabbitmq"
     depends_on:
       - basketdb
       - rabbitmq
     ports:
       - "8001:80"

       #add discount
   discount.api:
     container_name: discount.api
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
     depends_on:
       - discountdb
     ports:
       - "8002:80"


   orderapi:
      container_name: orderapi
      restart: on-failure
      environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionStrings:OrderConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=abdo12345"
          - "EventBus:HostName=rabbitmq"
      depends_on:
          - orderdb
          - rabbitmq
      volumes:
          - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
          - ${HOME}/.aspnet/https:/root/.aspnet/https/
      ports:
         - "8005:80"


   ocelotapigw:
      container_name: ocelotapigw
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        #- "ElasticConfiguration:Uri=http://elasticsearch:9200"
      depends_on:
        - catalogapi
        - basketapii
        - discount.api
        - orderapi
      ports:
        - "8010:80"

